#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

#;bspc rule -a Gimp desktop='^8' state=floating follow=on
#;bspc rule -a Chromium desktop='^2'
#;bspc rule -a mplayer2 state=floating
#;bspc rule -a Kupfer.py focus=on
#;bspc rule -a Screenkey manage=off


# Set specific applications to open in specific workspaces
bspc rule -a spotify-launcher desktop='^1'
bspc rule -a spotify-launcher state=floating 
bspc rule -a spotify-launcher follow=off
bspc rule -a TelegramDesktop desktop='^3' 
bspc rule -a TelegramDesktop follow=off
bspc rule -a discord desktop='^3' 
bspc rule -a discord follow=off
bspc rule -a firefox desktop='^2' follow=on

~/.config/polybar/material/launch.sh &
/home/wraient/.hidden/archsetup/startup_git_sync.sh
auto_git

firefox &
telegram-desktop &
discord &
spotify-launcher &

newlook &
picom &



